name: Reusable Deploy
on: 
  workflow_call:
    inputs:
      artifact-name:
        description: Deployable artifacts file
        required: false
        default: dist
        type: string
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v3
        with: ${{ inputs.artifact-name }}
      - name: List Files
        run: ls
      - name: Output Information
        run: echo "Deploying and uploading..."